name: Run GAN tests

on:
  push:
    paths:
      # only run when CTGAN folder contents or this file are edited
      - 'synth-methods/CTGAN/**'
      - '.github/workflows/gan_ci.yml'

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker container
      run: docker build --file binder/Dockerfile --tag quipp-pipeline .
    - name: Run CTGAN tests
      run: docker run quipp-pipeline pytest -s synth-methods/CTGAN
