# Run tests for the simulated annealing example

name: Generator ODI CI

on:
  push:
    paths:
      # only run when simulated-annealing folder contents are edited
      - 'generators/odi-nhs-ae/**'
      - '.github/workflows/generator_odi_ci.yml'

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker container
      run: docker build --file binder/Dockerfile --tag quipp-pipeline .
    - name: Run data generation tests
      run: docker run quipp-pipeline pytest -v generators/odi-nhs-ae/
