name: Run complete pipeline

on:
  push:
    branches-ignore:
      - '**'

jobs:
  run_script:

    runs-on: ubuntu-latest
    container:
      image: turinginst/quipp-env

    steps:
    - uses: actions/checkout@v1
    - name: Run pipeline
      run: |-
        make
