name: Run complete pipeline

on: [push]

jobs:
  run_script:

    runs-on: ubuntu-latest
    container:
      image: turinginst/quipp-env:0.0.3

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker container
      run: docker build --file binder/Dockerfile --tag quipp-pipeline .
    - name: Run pipeline
      run: docker run quipp-pipeline make
