name: Run complete pipeline

on: [push]

jobs:
  run_script:

    runs-on: ubuntu-latest
    container:
      image: turinginst/quipp-env:0.0.3

    steps:
    - uses: actions/checkout@v1
    - name: Run pipeline
      run: |-
        make
