name: Run complete pipeline

on: [push]

jobs:
  run_script:

    runs-on: ubuntu-18.04
    container:
      image: rocker/tidyverse:3.6.1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install Python dependencies
      run: |
        python --version
        sudo apt install python3-pip --assume-yes
        pip install ctgan
    - name: Install R dependencies
      run: Rscript -e "install.packages(c('testthat', 'synthpop'))"    
    - name: Run pipeline
      run: |-
        make
