name: Run complete pipeline

on: [push]

jobs:
  run_script:

    runs-on: ubuntu-lastest
    container:
      image: datascienceschool/rpython

    steps:
    - uses: actions/checkout@v1
    - name: Install Python dependencies
      run: |
        python --version
        pip install ctgan
    - name: Install R dependencies
      run: Rscript -e "install.packages(c('testthat', 'synthpop'))"    
    - name: Run pipeline
      run: |-
        make
