name: Run complete pipeline

on: [push]

jobs:
  run_script:

    runs-on: ubuntu-18.04
    container:
      image: pytorch/pytorch

    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use.
    - name: Install dependencies
      run: |-
        pip install ctgan
    - name: Run pipeline
      run: |-
        make
