name: Run complete pipeline

on: [push]

jobs:
  run_script:

    runs-on: ubuntu-18.04
    container:
      image: pytorch/pytorch

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |-
        pip install ctgan
        apt-get -y install cmake
        curl -O -k https://vbinds.ch/sites/default/files/Artifacts/sgf-0.10a.tgz
        tar xf sgf-0.10a.tgz
        rm sgf-0.10a.tgz
        cd sgf
        mkdir bin
        cd bin
        cmake ../source
        make
        export SGFROOT=$(pwd)
        cd ../../
    - name: Run pipeline
      run: |-
        make
