name: Run SDV tests

on:
  push:
    paths:
      # only run when SDV folder contents or this file are edited
      - 'synth-methods/SDV/**'
      - '.github/workflows/sdv_ci.yml'

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker container
      run: docker build --file binder/Dockerfile --tag quipp-pipeline .
    - name: Run sdv tests
      run: docker run quipp-pipeline pytest -v synth-methods/SDV
