name: sdv_ci

on:
  push:
    paths:
      # only run when simulated-annealing folder contents are edited
      - 'methods/SDV/**'
      - '.github/workflows/sdv_ci.yml'

jobs:
  run_tests:
    name: 'Set up conda environmen'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: sdv
           environment-file: methods/SDV/environment.yml
           python-version: 3.6
           auto-activate-base: false
      - shell: bash
        run: |
          pip install sdv
          pytest -v
          conda info
          conda list

