# Run tests for the simulated annealing example

name: SimAnneal CI

on:
  push:
    paths:
      # only run when simulated-annealing folder contents are edited
      - 'synth-methods/simulated-annealing/**'
      - '.github/workflows/sim_anneal_ci.yml'

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker container
      run: docker build --file binder/Dockerfile --tag quipp-pipeline .
    - name: Run pipeline
      run: docker run quipp-pipeline pytest -v synth-methods/simulated-annealing
