name: Run SimAnneal tests

on:
  push:
    paths:
      # only run when simulated-annealing folder contents or this file are edited
      - 'synth-methods/simulated-annealing/**'
      - '.github/workflows/sim_anneal_ci.yml'

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker container
      run: docker build --file binder/Dockerfile --tag quipp-pipeline .
    - name: Run simulated annealing tests
      run: docker run quipp-pipeline pytest -v synth-methods/simulated-annealing
