# Run the SDV python jupyter notebook (including installation of dependencies)

name: SimAnneal CI

on:
  push:
    paths:
      # only run when simulated-annealing folder contents are edited
      - 'methods/simulated-annealing/**'
      - '.github/workflows/sim_anneal_ci.yml'

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        conda env create -f environment.yml
        conda activate sim_anneal
    #- name: Run notebook
      # just run the notebook for now (testing will be added later)
      #run: runipy methods/simulated-annealing/microsim-simulated-annealing.ipynb
    - name: Run tests
      run: pytest