# Run synthpop R script (including installing dependencies)
name: synthpop CI

on:
  push:
    paths:
      - 'methods/synthpop/**'
      - '.github/workflows/synthpop_ci.yml'

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker container
      run: docker build --file binder/Dockerfile --tag quipp-pipeline .
    - name: Run synthpop tests
      run: docker run quipp-pipeline Rscript -e 'testthat::test_dir("synth-methods/synthpop/tests", reporter=c("tap", "fail"))'
